/**
 * BLACKTHORN install page — one-click download + step-by-step instructions.
 *
 * Detects the visitor's browser, surfaces the right .zip download button at the
 * top, and walks them through "Load unpacked" since the extension isn't on the
 * Chrome Web Store / AMO yet (hackathon-stage). When we publish, swap the
 * download for a CWS / AMO link and keep the same page shape.
 *
 * The .zip artefacts live in /apps/showcase/public/ (Vite serves them as static
 * assets from the showcase root). They're regenerated by the extension's build
 * postscript so this page always points to the latest build.
 */

import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  ArrowLeft, Download, Chrome, Globe2, ShieldCheck, ExternalLink,
  Sparkles, Lock, Cpu, Eye, ChevronRight, Check,
} from "lucide-react";

type Browser = "chrome" | "firefox" | "other";

interface ArtefactSpec {
  label: string;
  href: string;
  size?: string;
  emptyHint?: string;
}

const ARTEFACTS: Record<Exclude<Browser, "other">, ArtefactSpec> = {
  chrome:  { label: "BLACKTHORN for Chrome / Brave / Edge", href: "/blackthorn-chrome.zip" },
  firefox: { label: "BLACKTHORN for Firefox",               href: "/blackthorn-firefox.zip" },
};

function detectBrowser(): Browser {
  if (typeof navigator === "undefined") return "other";
  const ua = navigator.userAgent;
  if (/Firefox\//.test(ua)) return "firefox";
  if (/Chrome\/|Chromium\/|Edg\/|Brave\//.test(ua)) return "chrome";
  return "other";
}

export default function InstallPage() {
  const [browser, setBrowser] = useState<Browser>("other");
  const [downloadedKey, setDownloadedKey] = useState<string | null>(null);

  useEffect(() => { setBrowser(detectBrowser()); }, []);

  const primaryKey = browser === "firefox" ? "firefox" : "chrome";
  const alt = primaryKey === "chrome" ? "firefox" : "chrome";

  return (
    <div className="min-h-screen text-white" style={{ background: "#08070d" }}>
      <Link to="/" className="fixed top-4 left-4 z-50 flex items-center gap-1.5 text-xs text-white/30 hover:text-white/70 transition-colors">
        <ArrowLeft size={12} /> Showcase
      </Link>

      <header className="border-b border-white/5">
        <div className="max-w-3xl mx-auto px-6 py-5 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg flex items-center justify-center"
                 style={{ background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.12)" }}>
              <ShieldCheck size={14} className="text-white" />
            </div>
            <span className="font-bold tracking-tight">BLACKTHORN</span>
          </div>
          <span className="text-xs text-white/30">Get the wallet</span>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 pt-12 pb-20 space-y-10">
        <motion.section initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="text-4xl sm:text-5xl font-black tracking-tight leading-[1.05]">
            Install BLACKTHORN<br />
            <span style={{ background: "linear-gradient(135deg,#ffffff,#a78bfa)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
              in under a minute.
            </span>
          </h1>
          <p className="text-white/45 mt-4 leading-relaxed max-w-xl">
            A Solana smart wallet built on Swig with a transaction firewall. Pre-sign
            simulation, per-site policy, x402 payment caps — all enforced before your
            keys ever sign.
          </p>
        </motion.section>

        {/* Download card */}
        <motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
          <DownloadCard
            primary={{ key: primaryKey, spec: ARTEFACTS[primaryKey] }}
            alt={{ key: alt, spec: ARTEFACTS[alt] }}
            detectedBrowser={browser}
            downloadedKey={downloadedKey}
            onDownload={(k) => setDownloadedKey(k)}
          />
        </motion.section>

        {/* Install steps */}
        <motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
          <h2 className="text-sm uppercase tracking-wider text-white/40 font-semibold mb-4">Three steps to live</h2>
          {primaryKey === "chrome" ? <ChromeSteps downloaded={downloadedKey === "chrome"} /> : <FirefoxSteps downloaded={downloadedKey === "firefox"} />}
        </motion.section>

        {/* Why */}
        <motion.section initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.3 }}>
          <h2 className="text-sm uppercase tracking-wider text-white/40 font-semibold mb-4">Why this wallet</h2>
          <div className="grid sm:grid-cols-3 gap-2">
            <Feature icon={Eye}        title="Pre-sign simulation" body="Every tx is decoded + simulated before the popup even asks you to sign." />
            <Feature icon={Cpu}        title="x402 firewall"        body="HTTP 402 payments are gated by your hourly/daily caps, anomaly checks, allowlists." />
            <Feature icon={Lock}       title="On-chain revoke"      body="Per-site Swig sub-keys you can yank with one tap — the rug pull antidote." />
          </div>
        </motion.section>

        <motion.section initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4 }}
          className="rounded-2xl p-5"
          style={{ background: "rgba(255,255,255,0.025)", border: "1px solid rgba(255,255,255,0.06)" }}
        >
          <div className="flex items-start gap-3">
            <Sparkles size={16} className="text-violet-300 mt-0.5 shrink-0" />
            <div>
              <p className="text-sm font-semibold">After install, head to the showcase</p>
              <p className="text-white/45 text-xs mt-1 leading-relaxed">
                Each demo site lets you connect BLACKTHORN (or another Wallet Standard wallet)
                and triggers a different attack scenario so you can see the firewall in action.
              </p>
              <Link to="/" className="inline-flex items-center gap-1 text-xs text-violet-300 hover:text-violet-200 mt-2">
                Open showcase <ChevronRight size={12} />
              </Link>
            </div>
          </div>
        </motion.section>
      </main>
    </div>
  );
}

/* ───────────── pieces ───────────── */

function DownloadCard({
  primary, alt, detectedBrowser, downloadedKey, onDownload,
}: {
  primary: { key: Exclude<Browser, "other">; spec: ArtefactSpec };
  alt:     { key: Exclude<Browser, "other">; spec: ArtefactSpec };
  detectedBrowser: Browser;
  downloadedKey: string | null;
  onDownload: (key: Exclude<Browser, "other">) => void;
}) {
  const detectedCopy =
    detectedBrowser === "firefox" ? "We detected Firefox." :
    detectedBrowser === "chrome"  ? "We detected a Chromium browser (Chrome / Brave / Edge)." :
                                    "Pick the build for your browser.";

  return (
    <div className="rounded-2xl p-6"
         style={{ background: "linear-gradient(135deg, rgba(167,139,250,0.08), rgba(167,139,250,0.02))", border: "1px solid rgba(167,139,250,0.25)" }}>
      <p className="text-[11px] uppercase tracking-wider text-white/40 font-semibold mb-2">{detectedCopy}</p>

      <a
        href={primary.spec.href}
        download
        onClick={() => onDownload(primary.key)}
        className="flex items-center gap-4 p-4 rounded-xl transition-all hover:bg-white/[0.04]"
        style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.1)" }}
      >
        <div className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0"
             style={{ background: "linear-gradient(135deg,#ffffff,#c4b5fd)" }}>
          {primary.key === "chrome" ? <Chrome size={20} className="text-black" /> : <Globe2 size={20} className="text-black" />}
        </div>
        <div className="flex-1 min-w-0">
          <p className="font-bold">{primary.spec.label}</p>
          <p className="text-white/50 text-xs mt-0.5">
            {downloadedKey === primary.key ? "Downloaded ✓ — follow the steps below." : "Click to download the latest build."}
          </p>
        </div>
        {downloadedKey === primary.key
          ? <Check size={18} className="text-emerald-400 shrink-0" />
          : <Download size={16} className="text-white/60 shrink-0" />}
      </a>

      <a
        href={alt.spec.href}
        download
        onClick={() => onDownload(alt.key)}
        className="mt-2 flex items-center gap-3 px-3 py-2 rounded-lg text-xs transition-all hover:bg-white/[0.04]"
      >
        {alt.key === "chrome" ? <Chrome size={12} className="text-white/40" /> : <Globe2 size={12} className="text-white/40" />}
        <span className="text-white/45">Also available: <span className="text-white/70 underline">{alt.spec.label}</span></span>
        <Download size={11} className="text-white/30 ml-auto" />
      </a>
    </div>
  );
}

function ChromeSteps({ downloaded }: { downloaded: boolean }) {
  return (
    <ol className="space-y-3">
      <Step n="01" done={downloaded} title="Unzip the file">
        Right-click <code className="font-mono text-violet-300">blackthorn-chrome.zip</code> →
        Extract All. Remember the folder you extract it into.
      </Step>
      <Step n="02" title="Open chrome://extensions/">
        Paste <a className="font-mono text-violet-300 underline" href="chrome://extensions/" target="_blank" rel="noreferrer">chrome://extensions/</a> into your address bar (or Menu → Extensions → Manage). Toggle <b>Developer mode</b> on (top right).
      </Step>
      <Step n="03" title="Load unpacked">
        Click <b>"Load unpacked"</b> and pick the extracted <code className="font-mono text-violet-300">blackthorn-chrome</code> folder. BLACKTHORN appears in your toolbar. Click it to create your wallet.
      </Step>
    </ol>
  );
}

function FirefoxSteps({ downloaded }: { downloaded: boolean }) {
  return (
    <ol className="space-y-3">
      <Step n="01" done={downloaded} title="Unzip the file">
        Right-click <code className="font-mono text-violet-300">blackthorn-firefox.zip</code> →
        Extract Here. Remember the folder.
      </Step>
      <Step n="02" title="Open about:debugging">
        Paste <code className="font-mono text-violet-300">about:debugging#/runtime/this-firefox</code> into your address bar.
      </Step>
      <Step n="03" title="Load Temporary Add-on…">
        Click <b>"Load Temporary Add-on…"</b> and pick the <code className="font-mono text-violet-300">manifest.json</code> file inside the extracted folder.
        BLACKTHORN loads into your toolbar.
        <span className="block mt-1.5 text-white/40 text-[11px]">
          Note: Firefox temporary add-ons clear on restart — re-load after each browser restart.
        </span>
      </Step>
    </ol>
  );
}

function Step({ n, title, done, children }: { n: string; title: string; done?: boolean; children: React.ReactNode }) {
  return (
    <li className="flex items-start gap-4 p-4 rounded-xl"
        style={{ background: "rgba(255,255,255,0.025)", border: "1px solid rgba(255,255,255,0.06)" }}>
      <div className="w-9 h-9 rounded-full flex items-center justify-center font-mono text-xs font-bold shrink-0"
           style={{ background: done ? "rgba(52,211,153,0.18)" : "rgba(255,255,255,0.06)", color: done ? "#34d399" : "#fff" }}>
        {done ? <Check size={14} /> : n}
      </div>
      <div className="flex-1 min-w-0 pt-1">
        <p className="font-semibold text-sm">{title}</p>
        <p className="text-white/55 text-xs mt-1 leading-relaxed">{children}</p>
      </div>
    </li>
  );
}

function Feature({ icon: Icon, title, body }: { icon: typeof Eye; title: string; body: string }) {
  return (
    <div className="rounded-xl p-4"
         style={{ background: "rgba(255,255,255,0.025)", border: "1px solid rgba(255,255,255,0.06)" }}>
      <Icon size={16} className="text-violet-300 mb-2" />
      <p className="text-sm font-bold">{title}</p>
      <p className="text-white/45 text-xs mt-1 leading-snug">{body}</p>
    </div>
  );
}

// Re-export so other pages can build "Coming soon to Chrome Web Store" links cleanly.
export { ExternalLink };
